services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password
    networks:
      - inceptionNetwork
  
  # wordpress:
  #   container_name: wordpress
  #   build: ./requirements/wordpress
  #   environment:
  #     WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
  #     WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
  #     WORDPRESS_DB_PASSWORD_FILE: ${DB_PASSWORD_FILE}
  #     WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
  #     WORDPRESS_URL: ${WORDPRESS_URL}
  #     WORDPRESS_TITLE: ${WORDPRESS_TITLE}
  #     WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
  #     WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
  #     WORDPRESS_ADMIN_PASSWORD_FILE: ${DB_ROOT_PASSWORD_FILE}
  #   volumes:
  #     - wp_data:/var/www/html
  #   secrets:
  #     - db_root_password
  #     - db_password
  #   networks:
  #     - inceptionNetwork
  #   depends_on:
  #     - mariadb

  # nginx:
  #   container_name: nginx
  #   build: ./requirements/nginx
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - wp_data:/var/www/html
  #   networks:
  #     - inceptionNetwork
  #   depends_on:
  #     - wordpress

volumes:
  wp_data:
  db_data:

networks:
  inceptionNetwork:

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt